### ISSUE TITLE
Disabling CIS Level 2 Patching

### ISSUE THREAD

**Issue by picnicsecurity** [ansible-lockdown/RHEL8-CIS#135]
**Question**
I am fairly confident that the issue is with my syntax but I cannot seem to figure out how to call your role and have it run only CIS level 1 patching. 

Playbook
```
---
- name: RHEL CIS Hardening
  hosts: rheltester
  roles:
    - role: rhel_hardening
      tags:
        - level1-server
      vars:
        rhel8cis_level_1: true
        rhel8cis_level_2: false
        system_is_ec2: true
  vars:
    ansible_connection: ssh
    ansible_user: ec2-user
    ansible_ssh_private_key_file: ~/keys/privkey.pem
    ansible_ssh_extra_args: '-o StrictHostKeyChecking=no'
```

Hosts.ini
```
[rheltester]
a.b.c.d
```

Command
```
ansible-playbook -vv -i hosts.ini rhel-hardening-playbook.yml
```

Output
```
.
.
.
TASK [rhel_hardening : 1.7.1.3 | L2 | PATCH | Ensure SELinux policy is configured] ***********************************************************************************************************
task path: /Users/ps/IdeaProjects/ansible/roles/rhel_hardening/tasks/section_1/cis_1.7.1.x.yml:33
redirecting (type: modules) ansible.builtin.selinux to ansible.posix.selinux
[WARNING]: Reboot is required to set SELinux state to 'enforcing'
changed: [a.b.c.d] => {"changed": true, "configfile": "/etc/selinux/config", "msg": "Config SELinux state changed from 'disabled' to 'enforcing'", "policy": "targeted", "reboot_required": true, "state": "enforcing"}
```

It does the level 1 CIS patching just fine but it is also doing level 2 which I do not want.

**Environment (please complete the following information):**
 - ansible-playbook [core 2.11.3]
 - python version = 3.9.6 (default, Jun 29 2021, 05:25:02) [Clang 12.0.5 (clang-1205.0.22.9)]

**Comment by georgenalen** [comment]
Hello @picnicsecurity,

 Those aren't the vars you think they are... so the issue is kind of what you have but mostly a confusing element in defaults/main.yml that we need to add some comments around. The rhel8cis_level_1/rhel8cis_level_2 vars are not used for enabling/disabling the levels of control, they are used the goss auditing feature for compliance checking. 

 With that we do have tags for the levels on each of the controls. So you can add the --tags "level1-server,level1-workstation" to only run the level1 server/workstation controls. You can also use --skip-tags for the opposite to skip level2 server/workstation tasks as well. In Tower/AWX there is a tags/skip tags field as well and those would be listed there. 

 Let me know if using the tags helps and we will add some comments around the level_1/level_2 vars to make them less confusing. 

George

**Comment by picnicsecurity** [comment]
Ah gotcha that makes sense thank you for clarifying that. 


I thought me doing 

```
tags:
        - level1-server
```

Would have accomplished that?

I added the `--tags "level1-server,level1-workstation"` to my ansible command and it would appear to working exactly as desired. Have not seen a L2 pop up yet. What is the difference between level1-server and level1-workstation?

Thanks!

**Comment by picnicsecurity** [comment]
I also tried this syntax and it still did the L2 tasks 

```
---
- name: RHEL CIS Hardening
  #debugger: always
  hosts: rheltester
  roles:
    - { role: rhel_hardening, tags: ['level1-server', 'level1-workstation']}
```

**Comment by picnicsecurity** [comment]
@georgenalen when you have a chance can you take a look at this please? I haven't been able to figure out the syntax for calling your role yet. 

```
---
- name: RHEL CIS Hardening
  #debugger: always
  hosts: rheltester
  roles:
    - { role: rhel_hardening, tags: ['level1-server', 'level1-workstation']}
```

```
---
- name: RHEL CIS Hardening
  hosts: rheltester
  roles:
    - role: rhel_hardening
      tags:
        - level1-server
        - level1-workstation
```

Neither of the above work and Level 2 will apply to the hosts. The only thing that works is using the command `ansible-playbook rhel_cis_level_1.yml --tags "level1-workstation, level1-server"`.

**Comment by picnicsecurity** [comment]
@georgenalen have you had the chance to update how the tags work and or verify if I am using the tags correctly yet?

**Comment by uk-bolly** [comment]
hi @picnicsecurity 

Thank you for taking the time to confirm this. Apologies for the delay is responding, supported clients I'm afraid take priority. However you have raised a couple of things and some typos have appeared in the config (which will shortly be corrected in an upcoming release). Thank you again for highlighting this.

With regard to the questions, I am hoping to try and extend to comments added by @georgenalen 

## run level1 or level2
level1 generally lower risk to service disruption (although each circumstance is different)
level2 - greater risk of service disruption and other requirements that will affect a system. e.g. more space, selinux context etc

When wanting to call the relevant level to run on your system running as part of the playbook command is the way to ask for a tag to be used or skipped.

e.g.
```sh
ansible-playbook site.yml --tags level1-server 
```
or alternative
```sh
ansible-playbook site.yml --skip-tags level2-server
```
These both give the same result.

The examples you have provided 

```yml
---
- name: RHEL CIS Hardening
  hosts: rheltester
  roles:
    - role: rhel_hardening
      tags:
        - level1-server
        - level1-workstation
```

This has added a tag that can be used to call the role you have added, but doesn't define what the role will run. It will still run everything contained in the role if you ask for one of those tags.

## workstation or server
While there are cases where these will not stand the following generally explains the difference.
note: RedHat derivatives may not follow this setup.

- Server 
  - Tend not to have a gui and different functionality of the system (in RedHat this is the comment in /etc/redhat-release stating server) 
- Workstation 
  - Tend to be systems used as such (in the file /etc/redhat-release these normally have the label client or workstation) these also in majority of cases have a GUI installed.

I hope that this helps?

Best regards

uk-bolly
