### ISSUE TITLE
1.4.2 - Ansible 2.12 Does Not Manage /etc/crontab

### ISSUE THREAD

**Issue by ccravens** [ansible-lockdown/RHEL8-CIS#160]
**Describe the Issue**
Latest release of Ansible 2.12 seems to error out when managing /etc/crontab. When running step `1.4.2`, Ansible 2.12 will error with the following message:

```
TASK [/RHEL8-CIS : 1.4.2 | L1 | PATCH | Ensure filesystem integrity is regularly checked] ***
fatal: [example.com]: FAILED! => {"changed": false, "msg": "Will not manage /etc/crontab via cron_file, see documentation."}
```

Please refer to: https://docs.ansible.com/ansible-core/devel/collections/ansible/builtin/cron_module.html

```
The assumption is that this file is exclusively managed by the module, do not use if the file contains multiple entries, NEVER use for /etc/crontab.
```

**Expected Behavior**
While a user can modify the `rhel8cis_aide_cron`.`cron_file` setting, I would expect default configurations to handle this due to potentially unknown behavior when modifying default configurations.

**Actual Behavior**
Ansible will error and not modify the `/etc/crontab` file

**Control(s) Affected**
1.4.2

**Environment (please complete the following information):**
2.12

**Additional Notes**
None

**Possible Solution**
By updating the `rhel8cis_aide_cron` to the following, and creating a daily file within `/etc/cron.d`, the command works. However, I'm not sure if this is a valid approach.

```
# AIDE cron settings
rhel8cis_aide_cron:
    cron_user: root
    cron_file: /etc/cron.d/0daily   <<<< This is the only change required
    aide_job: '/usr/sbin/aide --check'
    aide_minute: 0
    aide_hour: 5
    aide_day: '*'
    aide_month: '*'
    aide_weekday: '*'
```
