### ISSUE TITLE
ansible_distribution_major_version should be treated as a string and not as an integer

### ISSUE THREAD

**Issue by xpillons** [ansible-lockdown/RHEL8-CIS#165]
**Describe the Issue**
pre_remediation_audit.yml is being skipped because ansible_distribution_major_version is tested as an integer and not as a string

**Expected Behavior**
Install git if not pesent

**Actual Behavior**
block "If using git for content set up" is skipped

**Control(s) Affected**
Audit failed to installed

**Environment (please complete the following information):**
 - Ansible Version: 2.9.6

**Possible Solution**
Compare to '8' and '7' instead of 8 and 7
```
- name: If using git for content set up
  block:
  - name: Install git (rh8 python3)
    package:
        name: git
        state: present
    when: ansible_distribution_major_version == '8'

  - name: Install git (rh7 python2)
    package:
        name: git
        state: present
    vars:
        ansible_python_interpreter: "{{ python2_bin }}"
    when: ansible_distribution_major_version == '7'

```
