### ISSUE TITLE
"2.2.10" task uses the wrong when conditional and tags

### ISSUE THREAD

**Issue by RayMcAdmin** [ansible-lockdown/RHEL8-CIS#176]
**Describe the Issue**
`name: "2.2.10 | PATCH | Ensure a web server is not installed"` uses the wrong when conditional and tags

**Expected Behavior**
`rhel8cis_rule_2_2_10` being set False should prevent the task block from running

**Actual Behavior**
The task runs irregardless because the when conditional is set to;

```
  when:
      - rhel8cis_rule_2_2_9
```
**Possible Solution**
```
- name: "2.2.10 | PATCH | Ensure a web server is not installed"
  block:
      - name: "2.2.10 | PATCH | Ensure a web server is not installed | Remove httpd server"
        package:
            name: httpd
            state: absent
        when:
            - not rhel8cis_httpd_server
            - "'httpd' in ansible_facts.packages"

      - name: "2.2.10 | PATCH | Ensure a web server is not installed | Remove nginx server"
        package:
            name: nginx
            state: absent
        when:
            - not rhel8cis_nginx_server
            - "'nginx' in ansible_facts.packages"
  when:
      - rhel8cis_rule_2_2_10
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - httpd
      - nginx
      - webserver
      - rule_2.2.10

```
