### ISSUE TITLE
4.2.1.x & 4.2.2.x

### ISSUE THREAD

**Issue by flwitten** [ansible-lockdown/RHEL8-CIS#185]
**Describe the Issue**
CIS Benchmark states the following:

- This section will cover the minimum best practices for the usage of **either** rsyslog **or** journald.

There is actually a condition for rsyslog but not for journald 
```
- name: "SECTION | 4.2.1.x| Configure rsyslog"
  include_tasks: cis_4.2.1.x.yml
  when: rhel8cis_syslog == 'rsyslog'

- name: "SECTION | 4.2.2.x| Configure journald"
  import_tasks: cis_4.2.2.x.yml
```
In addition if variable _rhel8cis_syslog_  is set to `'rsyslog'` there is a conflict:

```
- name: "4.2.1.3 | PATCH | Ensure journald is configured to send logs to rsyslog"
  lineinfile:
      path: /etc/systemd/journald.conf
      regexp: "^#ForwardToSyslog=|^ForwardToSyslog="
      line: ForwardToSyslog=yes
  when:
      - rhel8cis_rule_4_2_1_3

- name: "4.2.2.5 | PATCH | Ensure journald is not configured to send logs to rsyslog"
  lineinfile:
      path: /etc/systemd/journald.conf
      regexp: "^ForwardToSyslog="
      line: "#ForwardToSyslog=yes"
  notify: restart systemd_journal_upload
  when:
      - rhel8cis_rule_4_2_2_5
```
defaults/main.yml states:
```
# Syslog system - either rsyslog or syslog-ng
rhel8cis_syslog: rsyslog
rhel8cis_rsyslog_ansiblemanaged: true
```
Shouldn't that be rsyslog or journald?

**Expected Behavior**
Either rsyslog or journald should be configured

**Control(s) Affected**
4.2.x

**Environment (please complete the following information):**
 - Ansible Version: 2.11
 - Host Python Version: 3.6
 - Ansible Server Python Version: 3.6
 - Additional Details:
