### ISSUE TITLE
Hide userlist in GDM, is that a control?

### ISSUE THREAD

**Issue by Thulium-Drake** [ansible-lockdown/RHEL8-CIS#199]
**Question**
While looking into the rules for GDM (to debug a different issue) the following question arose:

Why doesn't GDM hide all users that previously logged in? Is that simply _not_ a CIS control?

It seems weird to me, as it's a form of information leakage :-)

In any case, if you need some code to set that up:

```yaml
---
- name: 'Ensure dconf profile'
  ansible.builtin.copy:
    dest: '/etc/dconf/profile/gdm'
    owner: 'root'
    group: 'root'
    mode: 0644
    content: |
      # This file is managed by Ansible, YOUR CHANGES WILL BE LOST!
      user-db:user
      system-db:gdm
      file-db:/usr/share/gdm/greeter-dconf-defaults

- name: 'Ensure GDM keyfile'
  ansible.builtin.copy:
    dest: '/etc/dconf/db/gdm.d/00-login-screen'
    owner: 'root'
    group: 'root'
    mode: 0644
    content: |
      # This file is managed by Ansible, YOUR CHANGES WILL BE LOST!
      [org/gnome/login-screen]
      # Do not show the user list
      disable-user-list=true

- name: 'Update dconf database'
  ansible.builtin.command: dconf update
  changed_when: false
```
