### ISSUE TITLE
rule 2.2.18 - nfs-utils should be changed to mask nfs-server

### ISSUE THREAD

**Issue by areh** [ansible-lockdown/RHEL8-CIS#235]
**Describe the Issue**
ipa-client depends on nfs-utils. Removing it in an enterprise environment would be catastrophic.

**Expected Behavior**
Securing nfs should not break the system.
ipa-client should never be allowed to be removed. 

**Actual Behavior**
nfs-server should be masked as per the CIS benchmark

**Control(s) Affected**
ipa-client could be removed, which would break an enterprise platform.

**Environment (please complete the following information):**
Not relevant

**Possible Solution**
Change code to something like this:
```
- name: "2.2.18 | PATCH | Ensure the nfs-server service is masked"
  systemd:
    name: nfs-server
    masked: yes
    state: stopped
```
