### ISSUE TITLE
rule 2.2.19 - should be changed to mask rpcbind service and rpcbind.socket

### ISSUE THREAD

**Issue by areh** [ansible-lockdown/RHEL8-CIS#236]
**Describe the Issue**
Similar to #235 
ipa-client depends on rpcbind. Removing it in an enterprise environment would be catastrophic.

**Expected Behavior**
Securing rpcbind should not break the system.
ipa-client should never be allowed to be removed. 

**Actual Behavior**
rpcbind and rpcbind.socket should be masked as per the CIS benchmark

**Control(s) Affected**
ipa-client could be removed, which would break an enterprise platform.

**Environment (please complete the following information):**
Not relevant

**Possible Solution**
Change code to something like this:
```
- name: "2.2.19 | PATCH | Ensure rpcbind and rpcbind.socket are masked"
  systemd:
    name: "{{ item }}"
    masked: yes
    state: stopped
  with_items:
    - rpcbind
    - rpcbind.socket
```
