### ISSUE TITLE
Rule 5.6.2 keying off gid, should be uid?

### ISSUE THREAD

**Issue by ikeusmaximus** [ansible-lockdown/RHEL8-CIS#249]
**Question**
Rule 5.6.2 is keying off gid (when item.gid), should be item.uid?

```
- name: "5.6.2 | PATCH | Ensure system accounts are secured"
  block:
      - name: "5.6.2 | Ensure system accounts are secured | Set nologin"
        user:
            name: "{{ item.id }}"
            shell: /usr/sbin/nologin
        with_items:
            - "{{ rhel8cis_passwd }}"
        when:
            - item.id != "root"
            - item.id != "sync"
            - item.id != "shutdown"
            - item.id != "halt"
            - item.**gid** < rhel8uid_interactive_uid_start | int
            - item.shell != "      /bin/false"
            - item.shell != "      /usr/sbin/nologin"
        loop_control:
            label: "{{ item.id }}"

      - name: "5.6.2 | PATCH | Ensure system accounts are secured | Lock accounts"
        user:
            name: "{{ item.id }}"
            password_lock: true
        with_items:
            - "{{ rhel8cis_passwd }}"
        when:
            - item.id != "halt"
            - item.id != "shutdown"
            - item.id != "sync"
            - item.id != "root"
            - item.id != "nfsnobody"
            - item**.gid** < rhel8uid_interactive_uid_start | int
            - item.shell != "      /bin/false"
            - item.shell != "      /usr/sbin/nologin"
        loop_control:
            label: "{{ item.id }}"
  when:
      - rhel8cis_rule_5_6_2
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - accounts
      - rule_5.6.2
 ```

**Environment (please complete the following information):**
 - Ansible Version: [e.g. 2.10] n/a
 - Host Python Version: [e.g. Python 3.7.6] n/a
 - Ansible Server Python Version: [e.g. Python 3.7.6] n/a
 - Additional Details:
