### ISSUE TITLE
oscap scanner reports a finding due to the use of double quotes.

### ISSUE THREAD

**Issue by bbaassssiiee** [ansible-lockdown/RHEL8-CIS#268]
Rule: 'Ensure Sudo Logfile Exists - sudo logfile' failed.

https://github.com/ansible-lockdown/RHEL8-CIS/blob/337856997d7189eda9c38ec77d57327631f91669/tasks/section_5/cis_5.3.x.yml#L35

**Comment by bbaassssiiee** [comment]
If this line would read like below the oscap scanner using the openscap security guide would pass.

```yaml
 line: 'Defaults logfile={{ rhel8cis_sudolog_location }}' 
 ```

**Comment by bbaassssiiee** [comment]
How to test:

```yaml
---

- name: Install openscap
  ansible.builtin.dnf:
      state: present
      name:
          - openscap-scanner
          - scap-security-guide

- name: Run CIS oscap scan and create /tmp/report.html
  ansible.builtin.command:
      oscap xccdf eval \
          --report /tmp/report.html
          --profile cis
          --fetch-remote-resources
          /usr/share/xml/scap/ssg/content/ssg-almalinux8-ds.xml
  changed_when: true
  no_log: false
  ignore_errors: true
```
