### ISSUE TITLE
CIS-CAT-PRO audit finding 4.2.2.3

### ISSUE THREAD

**Issue by bbaassssiiee** [ansible-lockdown/RHEL8-CIS#279]
**Describe the Issue**

Description:

The journald system includes the capability of compressing overly large files to avoid filling up the system with logs or making the logs unmanageably large.

Uncompressed large files may unexpectedly fill a filesystem leading to resource unavailability. Compressing logs prior to write can prevent sudden, unexpected filesystem impacts.

Edit the /etc/systemd/journald.conf file and add the following line:
```
Compress=yes 
```

**Expected Behavior**
Explicitly defined. No quotes around `yes`, not commented.

**Actual Behavior**
The line is still commented and shouldn't be.

**Control(s) Affected**
What controls are being affected by the issue: CIS 4.2.2.3

**Environment (please complete the following information):**
 - Ansible Version:  [core 2.11.12] 
 - Host Python Version: [Python 3.6.8]
 - Ansible Server Python Version: [Python 3.6.8]
 - Using branch: [release 2.2.1]
 - Additional Details: 

**Additional Notes**
CIS-CAT_PRO is the official audit tool for CIS members.

**Possible Solution**
Enter a suggested fix here

```yaml
- name: Insert correct line to /etc/systemd/journald.conf
  ansible.builtin.lineinfile:
    path: /etc/systemd/journald.conf
    create: true
    regexp: 'Compress='
    line: Compress=yes
    state: present
    insertafter: ^#Compress
    validate: /usr/bin/bash -n %s
```
