### ISSUE TITLE
CIS-CAT-PRO audit finding 4.2.2.4

### ISSUE THREAD

**Issue by bbaassssiiee** [ansible-lockdown/RHEL8-CIS#280]
**Description:**

Ensure journald is configured to write logfiles to persistent disk

Data from journald may be stored in volatile memory or persisted locally on the server. Logs in memory will be lost upon a system reboot. By persisting logs to local disk on the server they are protected from loss due to a reboot.

Writing log data to disk will provide the ability to forensically reconstruct events which may have impacted the operations or security of a system even after a system crash or reboot.

Edit the /etc/systemd/journald.conf file and add the following line:

```
Storage=persistent 
```

**Expected Behavior**
The line is explicit and uncommented.

**Actual Behavior**
The line is commented, as if the regexp didn't match for some reason.

**Control(s) Affected**
What controls are being affected by the issue: CIS 4.2.2.4

**Environment (please complete the following information):**
 - Ansible Version:  [core 2.11.12] 
 - Host Python Version: [Python 3.6.8]
 - Ansible Server Python Version: [Python 3.6.8]
 - Using branch: [release 2.2.1]
 - Additional Details: 

**Additional Notes**
CIS-CAT_PRO is the official audit tool for CIS members.

**Possible Solution**
Enter a suggested fix here

```yaml
- name: Insert correct line to /etc/systemd/journald.conf
  ansible.builtin.lineinfile:
    path: /etc/systemd/journald.conf
    create: true
    regexp: 'Storage='
    line: Storage=persistent
    state: present
    insertafter: ^#Storage
    validate: /usr/bin/bash -n %s
```
