### ISSUE TITLE
Packages are updated, but old kernels are not removed

### ISSUE THREAD

**Issue by bbaassssiiee** [ansible-lockdown/RHEL8-CIS#287]
https://github.com/ansible-lockdown/RHEL8-CIS/blob/5bafd209ee999dd34599c5b387aec9993900e112/tasks/section_1/cis_1.9.yml#L3

Updating all packages is fine, but when the kernel is updated, older, possibly vulnerable, versions could be removed to mitigate booting with them.

In the spirit of CIS 1.9, maybe not valid in the strict interpretation...

**Comment by uk-bolly** [comment]
hi @bbaassssiiee 

Great idea, we could make this an optional. I would probably look at keeping the last 2(as default)? just for rollback purposes?
Good enhancement.

Cheers 

uk-bolly

**Comment by Thulium-Drake** [comment]
Hi @uk-bolly 

At work we use the following playbook include in our maintenance plays:

```
---
- name: 'Remove old kernel packages'
  hosts: 'all'
  tasks:
    - name: 'Uninstall old kernels'
      ansible.builtin.shell: yum remove $(yum repoquery --installonly --latest-limit=-2 -q)
      when: ansible_facts['os_family'] == 'RedHat'
```

That might give you a head stat ;-)
