### ISSUE TITLE
Ensure SSH X11 forwarding is disabled task only fixes first occurence

### ISSUE THREAD

**Issue by fgierlinger** [ansible-lockdown/RHEL8-CIS#380]
**Describe the Issue**
The hardening guide requires to disable X11 forwarding unless there is an operational requirement. The [task 5.2.12](https://github.com/ansible-lockdown/RHEL8-CIS/blob/bc4cdf885ce563ec9682caf65131bda9cb38277e/tasks/section_5/cis_5.2.x.yml#L229-L242) accomplishes this with the lineinfile module. lineinfile only replaces the first occurrence of X11Forwarding. But X11Forwarding can appear multiple times in the ssh config. Once as a general option and once as an user option.

**Expected Behavior**
All occurences of _X11Forwarding_ should be disabled by the playbook.

**Actual Behavior**
Only the first occurence of _X11Forwarding_ is disabled by the playbook.

**Control(s) Affected**
v8 4.8 Uninstall or Disable Unnecessary Services on Enterprise Assets and Software
v7 9.2 Ensure Only Approved Ports, Protocols and Services Are Running

**Environment (please complete the following information):**

- branch being used: tag 2.6.0 (bc4cdf885ce563ec9682caf65131bda9cb38277e)
- Ansible Version: 4.0.0 (core 2.11.12)
- Host Python Version: Python 3.11.5
- Ansible Server Python Version: Python 3.6.8
- Additional Details:

**Additional Notes**
MVE of sshd_config
```
X11Forwarding yes

Match User anoncvs
    X11Forwarding yes
```

**Possible Solution**
Use _replace_ instead of _lineinfile_ module. As there is a disabled _match user_ block in the default sshd_config, a regex match on lines starting with `#` cannot be used as it would enable the indented line in the block. This could cause a config error. Therefore, only lines that are already enabled are checked. The default value for `X11Forwarding` on RHEL8 is `no`.

```yaml
- name: "5.2.12 | PATCH | Ensure SSH X11 forwarding is disabled"
  ansible.builtin.replace:
      path: /etc/ssh/sshd_config
      regexp: '^(\s*)X11Forwarding.*'
      replace: '\1X11Forwarding no'
  when:
      - rhel8cis_rule_5_2_12
  tags:
      - level2-server
      - level1-workstation
      - automated
      - patch
      - ssh
      - rule_5.2.12
```
