### ISSUE TITLE
Look to add exclusions to controls 1.2.2 and 1.2.3

### ISSUE THREAD

**Issue by uk-bolly** [ansible-lockdown/RHEL8-CIS#431]
## Feature Request or Enhancement

- Feature Add Repo exclusions for those who don't support gpg the find could allow exception list

**Suggested Code**
```
- name: "1.2.2 | AUDIT | Ensure gpgcheck is globally activated | Find repos"
        ansible.builtin.find:
            paths: /etc/yum.repos.d
            patterns: "*.repo"
            excludes: "{{ rhel8cis_repo_gpgcheck_exclude }}"
        register: discovered_yum_repos
        changed_when: false

```

similar for the 1.2.3 repo_gpgcheck
