### ISSUE TITLE
Change `POST | Perform DNF package cleanup` task in `post.yml` to accurately reflect whether leaf packages have been removed or not.

### ISSUE THREAD

**Issue by tux-repos** [ansible-lockdown/RHEL8-CIS#434]
## Feature Request or Enhancement

- Feature []
- Enhancement [x]

**Summary of Request**
Currently this task always returns an "OK" output, regardless of any changes. This means that when leaf packages _are_ removed the output is exactly the same as when no packages are removed, painting an incorrect image of events.

This is because of a 'changed_when' conditional added at the end of the task, see below for my proposed fix.

**Suggested Code**
Current content `post.yml`
```
- name: POST | Perform DNF package cleanup
  ansible.builtin.dnf:
      autoremove: true
  changed_when: false
```

Proposed `post.yml`
```
- name: POST | Perform DNF package cleanup
  ansible.builtin.dnf:
      autoremove: true
```

Simply removing this line will make this task accurately report whether or not leaf packages have been removed by showing "Changed" when they are and "OK" when no leaf packages have been removed.
