### ISSUE TITLE
Playbook fails if no internet. Tries to download packages they already are in the system.

### ISSUE THREAD

**Issue by txsastre** [ansible-lockdown/RHEL8-CIS#442]
**Describe the Issue**
I have a few vm without internet, well almost all of them.
when trying the playbook it stops in 

TASK [/home/aemer/ansible/hardening/RHEL8-CIS : PRELIM | PATCH | Add the required packages] *****************

then I downloaded de packages to my controller,  uploaded to the host and installed.

executed again and same problem again.

**Expected Behavior**
I was expected once I installed the packages on the remote hosts I would not have that problem.

**Actual Behavior**
it stops and do not continue

**Control(s) Affected**
 

**Environment (please complete the following information):**

- branch being used: devel
 ansible --version
ansible [core 2.16.3]
  config file = /home/aemer/ansible/ansible.cfg
  configured module search path = ['/home/aemer/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.12/site-packages/ansible
  ansible collection location = /home/aemer/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.12.6 (main, Nov  5 2024, 12:52:47) [GCC 8.5.0 20210514 (Red Hat 8.5.0-22.0.1)] (/usr/bin/python3.12)
  jinja version = 3.1.2
  libyaml = True

**Possible Solution**
I know that 
- name: "PRELIM | PATCH | Add the required packages"
  tags:
      - always
  ansible.builtin.package:
      name:
          - python3-libselinux
          - python3-rpm
      state: present

should not bring error if the packaes are installed... but ther are, the difference is that they have been installed via rpm.

on the host I do:
rpm -q python3-libselinux python3-rpm
python3-libselinux-2.9-8.el8.x86_64
python3-rpm-4.14.3-31.0.3.el8.x86_64

so they are installed.

**Comment by txsastre** [comment]
as a possible solution I have modified the task this way in tasks\prelium.yml

```
- name: "PRELIM | PATCH | Add the required packages"
  tags:
      - always
  ansible.builtin.package:
      name:
          - python3-libselinux
          - python3-rpm
      state: present
      **disablerepo: "*"**

setting disablerepo disables external repositories and also it has worked.
```
